INSERT INTO exercicios (nome, objetivo, local, series, reps, instrucoes, parte) VALUES
-- Pernas
('Agachamento', 'melhorar a saúde', 'Academia', 3, 10, 'url_do_video_de_agachamento', 'Pernas'),
('Levantamento Terra', 'melhorar a saúde', 'Academia', 4, 8, 'url_do_video_de_levantamento_terra', 'Pernas'),
('Agachamento Sumô', 'criar massa muscular', 'Academia', 3, 10, 'url_do_video_de_agachamento_sumo', 'Pernas'),
('Stiff', 'criar massa muscular', 'Academia', 4, 10, 'url_do_video_de_stiff', 'Pernas'),
('Afundo', 'criar massa muscular', 'Academia', 3, 12, 'url_do_video_de_afundo', 'Pernas'),
('Agachamento Frontal', 'criar massa muscular', 'Academia', 3, 10, 'url_do_video_de_agachamento_frontal', 'Pernas'),
('Agachamento Livre', 'criar massa muscular', 'Academia', 4, 10, 'url_do_video_de_agachamento_livre', 'Pernas'),
('Afundo no Smith', 'criar massa muscular', 'Academia', 3, 10, 'url_do_video_de_afundo_no_smith', 'Pernas'),
('Agachamento Búlgaro', 'criar massa muscular', 'Academia', 3, 10, 'url_do_video_de_agachamento_bulgaro', 'Pernas'),
('Panturrilha no Leg Press', 'criar massa muscular', 'Academia', 4, 15, 'url_do_video_de_panturrilha_no_leg_press', 'Pernas'),
('Bicicleta no Ar', 'emagrecer', 'Em casa', 3, 20, 'url_do_video_de_bicicleta_no_ar', 'Pernas'),
('Elevação de Gêmeos Sentado', 'melhorar a saúde', 'Em casa', 4, 15, 'url_do_video_de_elevacao_de_gemelos_sentado', 'Pernas'),
('Saltos Alternados', 'emagrecer', 'Em casa', 3, 20, 'url_do_video_de_saltos_alternados', 'Pernas'),
('Leg Press 45°', 'emagrecer', 'Academia', 3, 15, 'url_do_video_de_leg_press_45', 'Pernas'),
('Panturrilha em Máquina Sentado', 'emagrecer', 'Academia', 4, 20, 'url_do_video_de_panturrilha_em_maquina_sentado', 'Pernas'),
('Afundo com Barra', 'emagrecer', 'Academia', 3, 15, 'url_do_video_de_afundo_com_barra', 'Pernas'),
('Leg Press Horizontal', 'melhorar a saúde', 'Academia', 3, 15, 'url_do_video_de_leg_press_horizontal', 'Pernas'),
('Panturrilha em Máquina em Pé', 'melhorar a saúde', 'Academia', 4, 20, 'url_do_video_de_panturrilha_em_maquina_em_pe', 'Pernas'),
('Afundo Lateral com Halteres', 'melhorar a saúde', 'Academia', 3, 15, 'url_do_video_de_afundo_lateral_com_halteres', 'Pernas'),
('Cadeira Flexora', 'melhorar a saúde', 'Academia', 4, 12, 'url_do_video_de_cadeira_flexora', 'Pernas'),
('Glúteo Máquina', 'melhorar a saúde', 'Academia', 3, 15, 'url_do_video_de_gluteo_maquina', 'Pernas'),

-- Tórax
('Supino Reto', 'criar massa muscular', 'Em casa', 3, 8, 'url_do_video_de_supino_reto', 'Tórax'),
('Flexão de Braço', 'emagrecer', 'Em casa', 3, 12, 'url_do_video_de_flexao_de_braco', 'Tórax'),
('Desenvolvimento de Ombro', 'criar massa muscular', 'Em casa', 3, 10, 'url_do_video_de_desenvolvimento_de_ombro', 'Tórax'),
('Flexão de Braço Inclinada', 'emagrecer', 'Em casa', 3, 12, 'url_do_video_de_flexao_de_braco_inclinada', 'Tórax'),
('Elevação Frontal', 'criar massa muscular', 'Em casa', 3, 12, 'url_do_video_de_elevacao_frontal', 'Tórax'),
('Flexão de Braço Diamante', 'emagrecer', 'Em casa', 3, 10, 'url_do_video_de_flexao_de_braco_diamante', 'Tórax'),
('Flexão de Braço Militar', 'emagrecer', 'Em casa', 3, 10, 'url_do_video_de_flexao_de_braco_militar', 'Tórax'),
('Tríceps na Polia Alta', 'criar massa muscular', 'Academia', 3, 12, 'url_do_video_de_triceps_na_polia_alta', 'Tórax'),
('Flexão de Braço com Pegada Fechada', 'emagrecer', 'Em casa', 3, 12, 'url_do_video_de_flexao_de_braco_com_pegada_fechada', 'Tórax'),
('Tríceps Testa', 'criar massa muscular', 'Em casa', 3, 12, 'url_do_video_de_triceps_testa', 'Tórax'),
('Extensão de Tríceps na Corda', 'criar massa muscular', 'Academia', 3, 12, 'url_do_video_de_extensao_de_triceps_na_corda', 'Tórax'),
('Flexão de Braço com Apoio', 'emagrecer', 'Em casa', 3, 12, 'url_do_video_de_flexao_de_braco_com_apoio', 'Tórax'),
('Supino Declinado', 'emagrecer', 'Academia', 3, 15, 'url_do_video_de_supino_declinado', 'Tórax'),
('Elevação Lateral Invertida', 'emagrecer', 'Academia', 4, 12, 'url_do_video_de_elevacao_lateral_invertida', 'Tórax'),
('Tríceps Pulley', 'emagrecer', 'Academia', 3, 15, 'url_do_video_de_triceps_pulley', 'Tórax'),
('Supino Declinado', 'melhorar a saúde', 'Academia', 3, 15, 'url_do_video_de_supino_declinado', 'Tórax'),
('Elevação Lateral Invertida', 'melhorar a saúde', 'Academia', 4, 12, 'url_do_video_de_elevacao_lateral_invertida', 'Tórax'),
('Tríceps Pulley', 'melhorar a saúde', 'Academia', 3, 15, 'url_do_video_de_triceps_pulley', 'Tórax'),
('Desenvolvimento Militar', 'melhorar a saúde', 'Academia', 3, 12, 'url_do_video_de_desenvolvimento_militar', 'Tórax'),
('Tríceps Mergulho', 'melhorar a saúde', 'Academia', 3, 15, 'url_do_video_de_triceps_mergulho', 'Tórax'),

-- Costas
('Puxada na Barra Fixa', 'criar massa muscular', 'Academia', 4, 10, 'url_do_video_de_puxada_na_barra_fixa', 'Costas'),
('Cadeira Extensora', 'criar massa muscular', 'Academia', 3, 12, 'url_do_video_de_cadeira_extensora', 'Costas'),
('Rosca Direta com Barra', 'criar massa muscular', 'Academia', 3, 10, 'url_do_video_de_rosca_direta_com_barra', 'Costas'),
('Remada Curvada', 'criar massa muscular', 'Academia', 4, 10, 'url_do_video_de_remada_curvada', 'Costas'),
('Rosca Martelo', 'criar massa muscular', 'Em casa', 3, 12, 'url_do_video_de_rosca_martelo', 'Costas'),
('Remada Cavalinho', 'criar massa muscular', 'Academia', 4, 12, 'url_do_video_de_remada_cavalinho', 'Costas'),
('Barra-fixa', 'criar massa muscular', 'Academia', 4, 8, 'url_do_video_de_barra_fixa', 'Costas'),
('Rosca Concentrada', 'criar massa muscular', 'Academia', 3, 12, 'url_do_video_de_rosca_concentrada', 'Costas'),
('Rosca Inversa', 'criar massa muscular', 'Em casa', 3, 12, 'url_do_video_de_rosca_inversa', 'Costas'),
('Abdominal na Prancha', 'emagrecer', 'Em casa', 3, 15, 'url_do_video_de_abdominal_na_prancha', 'Costas'),
('Prancha Lateral', 'melhorar a saúde', 'Em casa', 3, 0, 'url_do_video_de_prancha_lateral', 'Costas'),
('Abdominal Infra', 'emagrecer', 'Em casa', 3, 15, 'url_do_video_de_abdominal_infra', 'Costas'),
('Abdominal Supra', 'emagrecer', 'Em casa', 3, 15, 'url_do_video_de_abdominal_supra', 'Costas'),
('Abdominal Canivete', 'emagrecer', 'Em casa', 3, 15, 'url_do_video_de_abdominal_canivete', 'Costas'),
('Prancha com Elevação de Braço', 'melhorar a saúde', 'Em casa', 3, 0, 'url_do_video_de_prancha_com_elevacao_de_braco', 'Costas'),
('Prancha com Elevação de Perna', 'melhorar a saúde', 'Em casa', 3, 0, 'url_do_video_de_prancha_com_elevacao_de_perna', 'Costas'),
('Prancha com Rotação', 'melhorar a saúde', 'Em casa', 3, 0, 'url_do_video_de_prancha_com_rotacao', 'Costas'),
('Abdominal Oblíquo', 'emagrecer', 'Em casa', 3, 15, 'url_do_video_de_abdominal_obliquo', 'Costas'),
('Remada Alta', 'emagrecer', 'Academia', 3, 15, 'url_do_video_de_remada_alta', 'Costas'),
('Abdominal Bicicleta', 'emagrecer', 'Academia', 4, 20, 'url_do_video_de_abdominal_bicicleta', 'Costas'),
('Rosca Scott', 'emagrecer', 'Academia', 3, 15, 'url_do_video_de_rosca_scott', 'Costas'),
('Remada Alta', 'melhorar a saúde', 'Academia', 3, 15, 'url_do_video_de_remada_alta', 'Costas'),
('Abdominal Russo', 'melhorar a saúde', 'Academia', 4, 20, 'url_do_video_de_abdominal_russo', 'Costas'),
('Rosca Zottman', 'melhorar a saúde', 'Academia', 3, 15, 'url_do_video_de_rosca_zottman', 'Costas'),
('Puxada Frontal na Polia Alta', 'melhorar a saúde', 'Academia', 4, 12, 'url_do_video_de_puxada_frontal_na_polia_alta', 'Costas'),
('Rosca Direta com Halteres', 'melhorar a saúde', 'Academia', 3, 15, 'url_do_video_de_rosca_direta_com_halteres', 'Costas');
